version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: stldevs
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mysql
    env_file:
    - ./.env
    environment:
      DB: "root:${DB_ROOT_PASS}@tcp(mysql:3306)/stldevs"
